import {
    createAsyncThunk,
    createSlice,
} from '@reduxjs/toolkit';
import axios from 'axios';
import { toast } from 'react-toastify';
import type { RootState } from '../../store';
import { getCookies, getCookie, setCookie, deleteCookie } from 'cookies-next';

// here we are typing the types for the state
export type AuthState = {
    data: any;
    isLogin: boolean;
    pending: boolean;
    error: boolean;
    message: any;
};

const initialState: AuthState = {
    data: {},
    isLogin: false,
    pending: false,
    error: false,
    message: "",
};

const baseURL = process.env.API_ENDPOINT || "https://api-dev.dgcolony.com/";

// This action is what we will call using the dispatch in order to trigger the API call.
export const login = createAsyncThunk('auth/web/login', async (params: any) => {
    console.log(params, 'result')
    try {
        const response = await axios.post(`${baseURL}`);
        const { data, status } = response
        if (status == 201) {
            toast.success("sukses")
            setCookie('accessToken', data?.accessToken, { maxAge: 60 * 60 * 24 })
            return data
        } else {
            throw response
        }
    } catch (error: any) {
        console.log(error.message, "error")
        toast.error("error")
        return error.response.data
    }
});

export const authMe = createAsyncThunk('auth/me', async (params: any) => {
    try {
        const response = await axios.get(`${baseURL}`);
        const { data, status } = response
        if (status == 200) {
            toast.success("sukses")
            return data
        } else {
            throw response
        }
    } catch (error: any) {
        console.log(error.message, "error")
        toast.error("error")
        return error.response.data
    }
});

export const loginSlice = createSlice({
    name: 'login',
    initialState,
    reducers: {
        // leave this empty here
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices. 
    // Since this is an API call we have 3 possible outcomes: pending, fulfilled and rejected. We have made allocations for all 3 outcomes. 
    // Doing this is good practice as we can tap into the status of the API call and give our users an idea of what's happening in the background.
    extraReducers: builder => {
        builder
            .addCase(login.pending, state => {
                state.pending = true;
            })
            .addCase(login.fulfilled, (state, { payload }) => {
                return {
                    ...state,
                    pending: false,
                    error: false,
                    data: {
                        user: payload.user,
                        accessToken: payload.accessToken,
                        refreshToken: payload.refreshToken
                    },
                }
            })
            .addCase(login.rejected, (state, { payload }) => {
                state.pending = false;
                state.error = true;
                state.message = payload;
            })
            .addDefaultCase((state, action) => {
                let base = {
                    ...state,
                    ...action.state
                }
                return base
            })
    }
});

export const profileSlice = createSlice({
    name: 'my-profile',
    initialState,
    reducers: {
        // leave this empty here
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices. 
    // Since this is an API call we have 3 possible outcomes: pending, fulfilled and rejected. We have made allocations for all 3 outcomes. 
    // Doing this is good practice as we can tap into the status of the API call and give our users an idea of what's happening in the background.
    extraReducers: builder => {
        builder
            .addCase(authMe.pending, state => {
                state.pending = true;
            })
            .addCase(authMe.fulfilled, (state, { payload }) => {
                return {
                    ...state,
                    pending: false,
                    error: false,
                    data: {
                        ...state.data,
                        user: payload.user
                    },
                }
            })
            .addCase(authMe.rejected, (state, { payload }) => {
                state.pending = false;
                state.error = true;
                state.message = payload;
            })
            .addDefaultCase((state, action) => {
                let base = {
                    ...state,
                    ...action.state
                }
                return base
            })
    }
});


export const selectLogin = (state: RootState) => state.loginReducers;
export const selectAuth = (state: RootState) => state.profileReducers;

const loginReducers = loginSlice.reducer;
const profileReducers = profileSlice.reducer;

export { loginReducers, profileReducers };