import Head from 'next/head';
import Cards from '../components/Cards/Cards';
import Navbar from '../components/Navbar';

export default function Home(props: any) {
  console.log(process.env.API_ENDPOINT, 'res')
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-500">
        <Navbar />
        <Cards />
        <div>
          Welcome to Next.js Versions 12 Typescript
        </div>
      </main>
    </div>
  )
}
